
---
##### Playbook para instalacion y configuracion del ambiente de trabajo para        ########
##### la materia Administracion de base de datos                                    ########
##### Proyecto desarrollado para la catedra Actualizacion Tecnologica e Innovacion  ########

## play para los quipos linux
- name: Instalacion en ambientes Linux
  hosts: linux # indico el host o grupo de host para los que se realiza la tarea#
  become: true

  ## Aqui se realizan las tareas de instalacion de las herramientas seleccionadas en el formulario
  tasks:

    - name: realizo ping
      ping:

    - name: me aseguro que exista el directorio de instalacion
      file:
        path: /tmp/instalacion/ejecutables
        state: directory

    ## Este modulo realiza la instalacion de mysql si es que no esta instalado previamente
    ## Si mysql ya se encuentra instalado, no hace nada
    ## esto se debe a la clausula "State=present" 
    
    - name: valido la instalacion de mysql desde el repositorio apt
      apt:
        name: mysql-server
        state: present
      when: herramienta == "MySQL" or herramienta == "COMPLETO"


    - name: Valido que el servicio de mysql se encuentre levantado
      service:
        name: mysql
        state: started
      when: herramienta == "MySQL" or herramienta == "COMPLETO"

    ## Este modulo realiza la isntalacion de MongoDB si es que no se encuentra instalado previamente
    - name: valido la instalacion de MongoDB desde el repositorio apt
      apt:
        name: mongodb-org
        state: present
      when: herramienta == "MongoDB" or herramienta == "COMPLETO"


      
       
## Play para los equipos windows       
- name: Instalacion en equipos Windows
  hosts: windows

  tasks:
    - name: realizo ping a windows
      win_ping:

    - name: Creo el directorio de instalacion si no existe
      win_file:
        path: C:\Temp\instalacion\ejecutables
        state: directory

    - name: Copio instalador en la ruta de ejecutables
      ansible.windows.win_copy:
        src: /home/jorge/Documentos/mysql-installer-community-8.0.36.0.msi
        dest: C:\Temp\instalacion\ejecutables\