- name: prueba de modulo ping
  hosts: linux

  tasks:
    - name: realizo ping
      ping:
       
- name: prueba ping a windows
  hosts: windows

  tasks:
    - name: realizo ping a windows
      win_ping: