##### Playbook de prueba para conectarme a dos esquipos con sistema operativo diferente  ########

## play para los quipos linux
- name: prueba de modulo ping
  hosts: linux # indico el host o grupo de host para los que se realiza la tarea

  tasks:
    - name: realizo ping
      ping:
       
## Play para los equipos windows       
- name: prueba ping a windows
  hosts: windows

  tasks:
    - name: realizo ping a windows
      win_ping: